import { REPORT_SCHEMA_VERSION, type Report } from "./types";

export const sampleReport: Report = {
  schemaVersion: REPORT_SCHEMA_VERSION,
  id: "sample-report",
  productName: "Fruit Gummies Variety Pack (12 count)",
  summary: "Retail-ready fruit gummies with multi-flavor pack, priced for club channel buyers. Shows how we present cost, risk, and evidence without requiring signup.",
  category: "confectionery",
  confidence: "medium",
  evidenceLevel: "similar_import",
  estimateQuality: "trade_backed",
  signals: {
    hasImportEvidence: true,
    hasInternalSimilarRecords: true,
    hasSupplierCandidates: true,
    verificationStatus: "none",
  },
  baseline: {
    costRange: {
      conservative: {
        unitPrice: 1.35,
        shippingPerUnit: 0.6,
        dutyPerUnit: 0.16,
        feePerUnit: 0.06,
        totalLandedCost: 2.17,
      },
      standard: {
        unitPrice: 1.15,
        shippingPerUnit: 0.45,
        dutyPerUnit: 0.12,
        feePerUnit: 0.05,
        totalLandedCost: 1.77,
      },
      range: {
        shippingPerUnit: { p10: 0.38, p50: 0.45, p90: 0.68 },
        dutyPerUnit: { p10: 0.1, p50: 0.12, p90: 0.16 },
        feePerUnit: { p10: 0.04, p50: 0.05, p90: 0.07 },
        totalLandedCost: { p10: 1.62, p50: 1.77, p90: 2.32 },
        billableWeightKg: { p10: 0.12, p50: 0.14, p90: 0.18 },
      },
    },
    riskScores: {
      tariff: 38,
      compliance: 52,
      supply: 36,
      total: 42,
    },
    riskFlags: {
      tariff: {
        hsCodeRange: ["1704.90", "1901.90"],
        adCvdPossible: false,
        originSensitive: true,
      },
      compliance: {
        requiredCertifications: ["FDA Food Facility Registration"],
        labelingRisks: ["Allergen statement (gelatin)", "Nutrition facts layout"],
        recallHints: ["Seal integrity for multi-pack"],
      },
      supply: {
        moqRange: { min: 500, max: 5000, typical: 2000 },
        leadTimeRange: { min: 28, max: 55, typical: 40 },
        qcChecks: ["Verify inner bag seal", "Drop test outer cartons", "Humidity control during fill"],
      },
    },
    evidence: {
      types: ["similar_records", "category_based"],
      assumptions: {
        packaging: "12 units per inner, 6 inners per carton; retail pouch with euro hole",
        weight: "0.14kg per unit (with packaging)",
        volume: "0.0012 m³ per carton",
        incoterms: "FOB Shanghai",
        shippingMode: "Air Express",
        unitsPerCase: "72 units"
      },
      inferredInputs: {
        shippingMode: {
          value: "air",
          source: "from_category",
          confidence: 0.72,
          explanation: "Lightweight snack with shelf-life sensitivity",
        },
        unitWeightG: {
          value: 140,
          source: "from_category",
          confidence: 0.68,
          explanation: "Includes retail pouch and master carton",
        },
        unitVolumeM3: {
          value: 0.002,
          source: "from_category",
          confidence: 0.62,
          explanation: "Compact retail packaging",
        },
        dutyRate: {
          value: 0.09,
          source: "from_category",
          confidence: 0.7,
          explanation: "HS 1704 candy baseline with sugar content",
        },
        feesPerUnit: {
          value: 0.05,
          source: "assumed",
          confidence: 0.5,
          explanation: "Payment and handling fees for small lots",
        },
        shippingPerUnit: {
          value: 0.48,
          source: "from_category",
          confidence: 0.55,
          explanation: "Air parcel quotation from East China to US West coast",
        },
        unitsPerCase: 72,
      },
      items: [],
      lastAttemptAt: null,
      lastSuccessAt: "2024-02-15T12:00:00.000Z",
      lastResult: "found",
      lastErrorCode: null,
    },
  },
  verification: {
    status: "not_requested",
  },
  nextActions: [
    {
      title: "Confirm HS code with label photo",
      description: "Upload packaging photo so we can lock duty at the right rate (1704 vs. 1901).",
      estimatedTime: "24 hours",
    },
    {
      title: "Request landed quotes",
      description: "We can source 3 factories and confirm MOQ/lead time with customs-ready paperwork.",
      estimatedTime: "2-3 days",
    },
    {
      title: "Set logistics lane",
      description: "Pick air vs. ocean and carton pack to tighten landed cost and timeline.",
      estimatedTime: "Same day",
    },
  ],
  verifiedQuotes: {
    suppliers: [],
    updatedAt: "2024-02-15T12:00:00.000Z",
  },
  createdAt: "2024-02-10T10:00:00.000Z",
  updatedAt: "2024-02-15T12:00:00.000Z",
  _hsCandidatesCount: 2,
  _hasLandedCosts: true,
  _supplierCandidateCount: 6,
  _supplierRecommendedCount: 3,
  _supplierMatches: [
    {
      id: "demo-supplier-1",
      supplierName: "Jiangsu Sweet Foods Co., Ltd.",
      supplierId: "supplier-jiangsu-001",
      supplierRole: "Manufacturer",
      tier: "recommended",
      location: "Suzhou, China",
      confidence: "high",
      matchMode: "normal",
      evidenceLabel: "customs_matched",
      reasonBadges: ["Customs record", "Category match", "MOQ fit"],
      matchScore: 92,
    },
    {
      id: "demo-supplier-2",
      supplierName: "Shanghai Snack Holdings Ltd.",
      supplierId: "supplier-shanghai-002",
      supplierRole: "Manufacturer",
      tier: "recommended",
      location: "Shanghai, China",
      confidence: "high",
      matchMode: "normal",
      evidenceLabel: "customs_matched",
      reasonBadges: ["Customs record", "Product match"],
      matchScore: 88,
    },
    {
      id: "demo-supplier-3",
      supplierName: "Guangdong Candy Manufacturing",
      supplierId: "supplier-guangdong-003",
      supplierRole: "Manufacturer",
      tier: "recommended",
      location: "Dongguan, China",
      confidence: "medium",
      matchMode: "normal",
      evidenceLabel: "customs_company_only",
      reasonBadges: ["Category match", "Export verified"],
      matchScore: 78,
    },
    {
      id: "demo-supplier-4",
      supplierName: "Zhejiang Confectionery Group",
      supplierId: "supplier-zhejiang-004",
      supplierRole: "Manufacturer",
      tier: "candidate",
      location: "Hangzhou, China",
      confidence: "medium",
      matchMode: "normal",
      evidenceLabel: "db_keyword_only",
      reasonBadges: ["Keyword match"],
      matchScore: 65,
    },
    {
      id: "demo-supplier-5",
      supplierName: "Fujian Fruit Snacks Co.",
      supplierId: "supplier-fujian-005",
      supplierRole: "Manufacturer",
      tier: "candidate",
      location: "Xiamen, China",
      confidence: "low",
      matchMode: "normal",
      evidenceLabel: "signals_limited",
      reasonBadges: ["Category inferred"],
      matchScore: 52,
    },
  ],
  _decisionSupport: {
    hs: {
      customsCategoryText: "Sugar confectionery, gummy candies",
      status: "DRAFT",
      candidates: [
        {
          code: "1704.90.35",
          confidence: 0.72,
          rationale: "Sugar confectionery, not containing cocoa: Gummy candies",
          evidenceSnippet: "Similar imports under this code from China",
          source: "ANALYSIS",
        },
        {
          code: "1901.90.90",
          confidence: 0.45,
          rationale: "Food preparations NESOI - alternative if contains flour base",
          evidenceSnippet: "Used for mixed confectionery with starch base",
          source: "MARKET_ESTIMATE",
        },
      ],
    },
    dutyRate: {
      status: "DRAFT",
      rateMin: 4.5,
      rateMax: 6.4,
      rationale: "Standard MFN rate for gummy confectionery from China",
    },
    cost: {
      landedPerUnit: { min: 1.77, mid: 1.97, max: 2.17 },
      componentsPerUnit: {
        factoryUnitPrice: { min: 1.05, mid: 1.15, max: 1.35 },
        shipping: { min: 0.38, mid: 0.48, max: 0.68 },
        duty: { min: 0.10, mid: 0.12, max: 0.16 },
        fees: { min: 0.04, mid: 0.05, max: 0.07 },
      },
      confidenceTier: "medium",
      evidenceSummary: "Based on 18 similar import records",
      currency: "USD",
    },
    quantityPlanner: {
      options: [
        { quantity: 500, totalLanded: { min: 885, mid: 985, max: 1085 }, totalProfit: null },
        { quantity: 1000, totalLanded: { min: 1770, mid: 1970, max: 2170 }, totalProfit: null },
        { quantity: 2000, totalLanded: { min: 3540, mid: 3940, max: 4340 }, totalProfit: null },
      ],
    },
    profit: {
      shelfPrice: null,
      breakEvenPrice: { min: 1.77, mid: 1.97, max: 2.17 },
      targetMarginPrices: [
        { marginPercent: 20, requiredShelfPrice: { min: 2.21, mid: 2.46, max: 2.71 } },
        { marginPercent: 30, requiredShelfPrice: { min: 2.53, mid: 2.81, max: 3.10 } },
      ],
    },
    nexsupplyValue: {
      blockers: ["No verified factory quotes", "HS code not confirmed", "Duty rate estimated"],
      whatWeDo: ["Source 3+ factory quotes", "Confirm HS and duty", "Create execution plan"],
      expectedTimelineText: "Quotes in ~7 days",
      ctaPrimaryText: "Start verification",
      ctaSecondaryText: "Talk to an expert",
    },
  },
  _similarRecordsSample: [
    {
      exporterName: "Jiangsu Sweet Foods Co.",
      unit_price: 1.12,
      moq: 1200,
    },
    {
      exporterName: "Shanghai Snack Holdings",
      unit_price: 1.25,
      moq: 1500,
    },
  ],
};
