import { REPORT_SCHEMA_VERSION, type Report } from "./types";

export const sampleReport: Report = {
  schemaVersion: REPORT_SCHEMA_VERSION,
  id: "sample-report",
  productName: "Fruit Gummies Variety Pack (12 count)",
  summary: "Retail-ready fruit gummies with multi-flavor pack, priced for club channel buyers. Shows how we present cost, risk, and evidence without requiring signup.",
  category: "confectionery",
  confidence: "medium",
  evidenceLevel: "exact_import",
  estimateQuality: "verified",
  signals: {
    hasImportEvidence: true,
    hasInternalSimilarRecords: true,
    hasSupplierCandidates: true,
    verificationStatus: "none",
  },
  baseline: {
    costRange: {
      conservative: {
        unitPrice: 1.35,
        shippingPerUnit: 0.6,
        dutyPerUnit: 0.16,
        feePerUnit: 0.06,
        totalLandedCost: 2.17,
      },
      standard: {
        unitPrice: 1.15,
        shippingPerUnit: 0.45,
        dutyPerUnit: 0.12,
        feePerUnit: 0.05,
        totalLandedCost: 1.77,
      },
      range: {
        shippingPerUnit: { p10: 0.38, p50: 0.45, p90: 0.68 },
        dutyPerUnit: { p10: 0.1, p50: 0.12, p90: 0.16 },
        feePerUnit: { p10: 0.04, p50: 0.05, p90: 0.07 },
        totalLandedCost: { p10: 1.62, p50: 1.77, p90: 2.32 },
        billableWeightKg: { p10: 0.12, p50: 0.14, p90: 0.18 },
      },
    },
    riskScores: {
      tariff: 38,
      compliance: 52,
      supply: 36,
      total: 42,
    },
    riskFlags: {
      tariff: {
        hsCodeRange: ["1704.90", "1901.90"],
        adCvdPossible: false,
        originSensitive: true,
      },
      compliance: {
        requiredCertifications: ["FDA Food Facility Registration"],
        labelingRisks: ["Allergen statement (gelatin)", "Nutrition facts layout"],
        recallHints: ["Seal integrity for multi-pack"],
      },
      supply: {
        moqRange: { min: 500, max: 5000, typical: 2000 },
        leadTimeRange: { min: 28, max: 55, typical: 40 },
        qcChecks: ["Verify inner bag seal", "Drop test outer cartons", "Humidity control during fill"],
      },
    },
    evidence: {
      types: ["exact_records", "label_ocr", "hs_code_analysis"],
      assumptions: {
        packaging: "12 units per inner, 6 inners per carton; retail pouch with euro hole",
        weight: "0.14kg per unit (with packaging)",
        volume: "0.0012 m³ per carton",
        incoterms: "FOB Shanghai",
        shippingMode: "Air Express",
        unitsPerCase: "72 units"
      },
        inferredInputs: {
        shippingMode: {
          value: "air",
          source: "from_exact_import",
          provenance: "exact_import_records",
          confidence: 0.88,
          explanation: "Lightweight snack with shelf-life sensitivity - matched from exact import records",
        },
        unitWeightG: {
          value: 140,
          source: "from_label",
          provenance: "label_ocr",
          confidence: 0.92,
          explanation: "Extracted from label photo OCR - includes retail pouch and master carton",
        },
        unitVolumeM3: {
          value: 0.002,
          source: "from_exact_import",
          provenance: "exact_import_records",
          confidence: 0.85,
          explanation: "Matched from exact import records - compact retail packaging",
        },
        dutyRate: {
          value: 0.09,
          source: "from_hs_code",
          provenance: "hs_code_analysis",
          confidence: 0.90,
          explanation: "HS 1704.90 confirmed from customs records - candy baseline with sugar content",
        },
        originCountry: {
          value: "CN",
          source: "from_label",
          provenance: "label_ocr",
          confidence: 0.95,
          explanation: "Extracted from label photo - Made in China",
        },
        hsCode: {
          value: "1704.90",
          source: "from_exact_import",
          provenance: "exact_import_records",
          confidence: 0.92,
          explanation: "Matched from exact import records - Sugar confectionery",
        },
        feesPerUnit: {
          value: 0.05,
          source: "from_exact_import",
          provenance: "exact_import_records",
          confidence: 0.75,
          explanation: "Payment and handling fees from similar import records",
        },
        shippingPerUnit: {
          value: 0.48,
          source: "from_exact_import",
          provenance: "exact_import_records",
          confidence: 0.82,
          explanation: "Air parcel quotation from East China to US West coast - matched from exact imports",
        },
        unitsPerCase: 72,
      },
      items: [],
      lastAttemptAt: null,
      lastSuccessAt: "2024-02-15T12:00:00.000Z",
      lastResult: "found",
      lastErrorCode: null,
    },
  },
  verification: {
    status: "not_requested",
  },
  nextActions: [
    {
      title: "Confirm HS code with label photo",
      description: "Upload packaging photo so we can lock duty at the right rate (1704 vs. 1901).",
      estimatedTime: "24 hours",
    },
    {
      title: "Request landed quotes",
      description: "We can source 3 factories and confirm MOQ/lead time with customs-ready paperwork.",
      estimatedTime: "2-3 days",
    },
    {
      title: "Set logistics lane",
      description: "Pick air vs. ocean and carton pack to tighten landed cost and timeline.",
      estimatedTime: "Same day",
    },
  ],
  verifiedQuotes: {
    suppliers: [],
    updatedAt: "2024-02-15T12:00:00.000Z",
  },
  createdAt: "2024-02-10T10:00:00.000Z",
  updatedAt: "2024-02-15T12:00:00.000Z",
  // V2 normalized data
  v2: {
    costModel: {
      standard: {
        unitPrice: 1.15,
        shippingPerUnit: 0.45,
        dutyPerUnit: 0.12,
        feePerUnit: 0.05,
        totalLandedCost: 1.77,
      },
      conservative: {
        unitPrice: 1.35,
        shippingPerUnit: 0.6,
        dutyPerUnit: 0.16,
        feePerUnit: 0.06,
        totalLandedCost: 2.17,
      },
    },
    deliveredCostRange: {
      min: 1.77,
      max: 2.32,
    },
    hsCandidates: [
      { code: "1704.90", confidence: 0.85, rationale: "Sugar confectionery", evidenceSnippet: "Sugar confectionery (including white chocolate), not containing cocoa" },
      { code: "1901.90", confidence: 0.72, rationale: "Food preparations", evidenceSnippet: "Food preparations of goods of headings 0401 to 0404" },
    ],
    evidenceLevel: "similar_import",
    missingInputs: ["origin"],
    importKeyCompanies: [
      {
        companyName: "SWEET TREATS IMPORTS LLC",
        role: "Importer",
        shipmentsCount: 24,
        lastSeen: "2024-11-15",
        originCountry: "China",
        exampleDescription: "Fruit gummies variety pack 12 count",
        source: "internal_records",
      },
      {
        companyName: "CANDY DISTRIBUTORS INC",
        role: "Importer",
        shipmentsCount: 18,
        lastSeen: "2024-10-22",
        originCountry: "China",
        exampleDescription: "Assorted fruit gummies retail pack",
        source: "internal_records",
      },
    ],
  },
  // Supplier matches - recommended factories
  _supplierMatches: [
    {
      id: "supplier-1",
      supplierId: "FACTORY_SH_001",
      supplier_id: "FACTORY_SH_001",
      supplierName: "Shanghai Confectionery Co., Ltd.",
      supplier_name: "Shanghai Confectionery Co., Ltd.",
      supplierRole: "Manufacturer",
      matchMode: "normal",
      confidence: "high",
      evidenceLabel: "customs_matched",
      reasonBadges: [
        "Customs records: 12 exact matches",
        "Internal dataset: 45 related items, pricing coverage 78%",
        "Verified manufacturer with FDA registration",
      ],
      tier: "recommended",
      match_score: 92,
      rerank_score: 0.89,
      unit_price: 1.08,
      moq: 2000,
      lead_time: 35,
      currency: "USD",
      exact_match_count: 12,
      inferred_match_count: 0,
      flags: {
        evidence_strength: "strong",
        matched_anchors: ["product_name", "hs_code"],
        why_lines: [
          "Customs records: 12 exact matches",
          "Internal dataset: 45 related items, pricing coverage 78%",
          "Verified manufacturer with FDA registration",
        ],
        companyType: "Manufacturer",
      },
      evidence: {
        recordCount: 12,
        lastSeenDays: 45,
        productTypes: ["Gummies", "Candy"],
        evidenceSnippet: "Fruit gummies variety pack imported 12 times in last 6 months",
      },
      isVerifiedLead: true,
      isExcluded: false,
      country: "China",
      last_seen_date: "2024-11-15",
      shipment_count_12m: 24,
      _intel: {
        product_count: 45,
        price_coverage_pct: 78,
        last_seen_days: 45,
      },
      _enrichment: null,
      _profile: {
        country: "China",
        last_seen_date: "2024-11-15",
        shipment_count_12m: 24,
        role: "Manufacturer",
        role_reason: "Verified manufacturer with FDA registration",
      },
      _supplierType: "Manufacturer",
      _companyType: "Manufacturer",
      _exampleProducts: [
        { product_name: "Fruit Gummies 12-pack", category: "confectionery", unit_price: 1.08 },
        { product_name: "Mixed Fruit Jelly", category: "confectionery", unit_price: 0.95 },
      ],
    },
    {
      id: "supplier-2",
      supplierId: "FACTORY_GZ_002",
      supplier_id: "FACTORY_GZ_002",
      supplierName: "Guangzhou Sweet Manufacturing",
      supplier_name: "Guangzhou Sweet Manufacturing",
      supplierRole: "Manufacturer",
      matchMode: "normal",
      confidence: "medium",
      evidenceLabel: "customs_company_only",
      reasonBadges: [
        "Customs records: 8 company matches",
        "Internal dataset: 28 related items, pricing coverage 65%",
        "Established factory since 2015",
      ],
      tier: "recommended",
      match_score: 78,
      rerank_score: 0.76,
      unit_price: 1.12,
      moq: 1500,
      lead_time: 40,
      currency: "USD",
      exact_match_count: 0,
      inferred_match_count: 8,
      flags: {
        evidence_strength: "medium",
        matched_anchors: ["hs_code"],
        why_lines: [
          "Customs records: 8 company matches",
          "Internal dataset: 28 related items, pricing coverage 65%",
          "Established factory since 2015",
        ],
        companyType: "Manufacturer",
      },
      evidence: {
        recordCount: 8,
        lastSeenDays: 62,
        productTypes: ["Confectionery", "Gummies"],
        evidenceSnippet: "Similar confectionery products imported regularly",
      },
      isVerifiedLead: true,
      isExcluded: false,
      country: "China",
      last_seen_date: "2024-10-22",
      shipment_count_12m: 18,
      _intel: {
        product_count: 28,
        price_coverage_pct: 65,
        last_seen_days: 62,
      },
      _enrichment: null,
      _profile: {
        country: "China",
        last_seen_date: "2024-10-22",
        shipment_count_12m: 18,
        role: "Manufacturer",
        role_reason: "Established factory since 2015",
      },
      _supplierType: "Manufacturer",
      _companyType: "Manufacturer",
      _exampleProducts: [
        { product_name: "Sweet Gummies Mix", category: "confectionery", unit_price: 1.12 },
      ],
    },
    {
      id: "supplier-3",
      supplierId: "FACTORY_SZ_003",
      supplier_id: "FACTORY_SZ_003",
      supplierName: "Shenzhen Candy Factory",
      supplier_name: "Shenzhen Candy Factory",
      supplierRole: "Manufacturer",
      matchMode: "normal",
      confidence: "medium",
      evidenceLabel: "db_keyword_only",
      reasonBadges: [
        "Internal dataset: 15 related items, pricing coverage 45%",
        "Keyword match: fruit gummies",
        "MOQ flexible, good for small orders",
      ],
      tier: "candidate",
      match_score: 65,
      rerank_score: 0.62,
      unit_price: 1.18,
      moq: 1000,
      lead_time: 45,
      currency: "USD",
      exact_match_count: 0,
      inferred_match_count: 0,
      flags: {
        evidence_strength: "weak",
        matched_anchors: ["keywords"],
        why_lines: [
          "Internal dataset: 15 related items, pricing coverage 45%",
          "Keyword match: fruit gummies",
          "MOQ flexible, good for small orders",
        ],
        companyType: "Manufacturer",
      },
      evidence: {
        recordCount: 0,
        lastSeenDays: null,
        productTypes: ["Candy"],
        evidenceSnippet: "Keyword match in product database",
      },
      isVerifiedLead: false,
      isExcluded: false,
      country: "China",
      last_seen_date: null,
      shipment_count_12m: 0,
      _intel: {
        product_count: 15,
        price_coverage_pct: 45,
        last_seen_days: null,
      },
      _enrichment: null,
      _profile: {
        country: "China",
        last_seen_date: null,
        shipment_count_12m: 0,
        role: "Manufacturer",
        role_reason: null,
      },
      _supplierType: "Manufacturer",
      _companyType: "Manufacturer",
      _exampleProducts: [],
    },
  ],
  _recommendedMatches: [
    {
      id: "supplier-1",
      supplierId: "FACTORY_SH_001",
      supplier_id: "FACTORY_SH_001",
      supplierName: "Shanghai Confectionery Co., Ltd.",
      supplier_name: "Shanghai Confectionery Co., Ltd.",
      supplierRole: "Manufacturer",
      matchMode: "normal",
      confidence: "high",
      evidenceLabel: "customs_matched",
      reasonBadges: [
        "Customs records: 12 exact matches",
        "Internal dataset: 45 related items, pricing coverage 78%",
        "Verified manufacturer with FDA registration",
      ],
      tier: "recommended",
      match_score: 92,
      rerank_score: 0.89,
      unit_price: 1.08,
      moq: 2000,
      lead_time: 35,
      currency: "USD",
      exact_match_count: 12,
      inferred_match_count: 0,
      flags: {
        evidence_strength: "strong",
        matched_anchors: ["product_name", "hs_code"],
        why_lines: [
          "Customs records: 12 exact matches",
          "Internal dataset: 45 related items, pricing coverage 78%",
          "Verified manufacturer with FDA registration",
        ],
        companyType: "Manufacturer",
      },
      evidence: {
        recordCount: 12,
        lastSeenDays: 45,
        productTypes: ["Gummies", "Candy"],
        evidenceSnippet: "Fruit gummies variety pack imported 12 times in last 6 months",
      },
      isVerifiedLead: true,
      isExcluded: false,
      country: "China",
      last_seen_date: "2024-11-15",
      shipment_count_12m: 24,
      _intel: {
        product_count: 45,
        price_coverage_pct: 78,
        last_seen_days: 45,
      },
      _enrichment: null,
      _profile: {
        country: "China",
        last_seen_date: "2024-11-15",
        shipment_count_12m: 24,
        role: "Manufacturer",
        role_reason: "Verified manufacturer with FDA registration",
      },
      _supplierType: "Manufacturer",
      _companyType: "Manufacturer",
      _exampleProducts: [
        { product_name: "Fruit Gummies 12-pack", category: "confectionery", unit_price: 1.08 },
        { product_name: "Mixed Fruit Jelly", category: "confectionery", unit_price: 0.95 },
      ],
    },
    {
      id: "supplier-2",
      supplierId: "FACTORY_GZ_002",
      supplier_id: "FACTORY_GZ_002",
      supplierName: "Guangzhou Sweet Manufacturing",
      supplier_name: "Guangzhou Sweet Manufacturing",
      supplierRole: "Manufacturer",
      matchMode: "normal",
      confidence: "medium",
      evidenceLabel: "customs_company_only",
      reasonBadges: [
        "Customs records: 8 company matches",
        "Internal dataset: 28 related items, pricing coverage 65%",
        "Established factory since 2015",
      ],
      tier: "recommended",
      match_score: 78,
      rerank_score: 0.76,
      unit_price: 1.12,
      moq: 1500,
      lead_time: 40,
      currency: "USD",
      exact_match_count: 0,
      inferred_match_count: 8,
      flags: {
        evidence_strength: "medium",
        matched_anchors: ["hs_code"],
        why_lines: [
          "Customs records: 8 company matches",
          "Internal dataset: 28 related items, pricing coverage 65%",
          "Established factory since 2015",
        ],
        companyType: "Manufacturer",
      },
      evidence: {
        recordCount: 8,
        lastSeenDays: 62,
        productTypes: ["Confectionery", "Gummies"],
        evidenceSnippet: "Similar confectionery products imported regularly",
      },
      isVerifiedLead: true,
      isExcluded: false,
      country: "China",
      last_seen_date: "2024-10-22",
      shipment_count_12m: 18,
      _intel: {
        product_count: 28,
        price_coverage_pct: 65,
        last_seen_days: 62,
      },
      _enrichment: null,
      _profile: {
        country: "China",
        last_seen_date: "2024-10-22",
        shipment_count_12m: 18,
        role: "Manufacturer",
        role_reason: "Established factory since 2015",
      },
      _supplierType: "Manufacturer",
      _companyType: "Manufacturer",
      _exampleProducts: [
        { product_name: "Sweet Gummies Mix", category: "confectionery", unit_price: 1.12 },
      ],
    },
  ],
  _candidateMatches: [
    {
      id: "supplier-3",
      supplierId: "FACTORY_SZ_003",
      supplier_id: "FACTORY_SZ_003",
      supplierName: "Shenzhen Candy Factory",
      supplier_name: "Shenzhen Candy Factory",
      supplierRole: "Manufacturer",
      matchMode: "normal",
      confidence: "medium",
      evidenceLabel: "db_keyword_only",
      reasonBadges: [
        "Internal dataset: 15 related items, pricing coverage 45%",
        "Keyword match: fruit gummies",
        "MOQ flexible, good for small orders",
      ],
      tier: "candidate",
      match_score: 65,
      rerank_score: 0.62,
      unit_price: 1.18,
      moq: 1000,
      lead_time: 45,
      currency: "USD",
      exact_match_count: 0,
      inferred_match_count: 0,
      reason_code: "keyword_match",
      flags: {
        evidence_strength: "weak",
        matched_anchors: ["keywords"],
        why_lines: [
          "Internal dataset: 15 related items, pricing coverage 45%",
          "Keyword match: fruit gummies",
          "MOQ flexible, good for small orders",
        ],
        companyType: "Manufacturer",
      },
      evidence: {
        recordCount: 0,
        lastSeenDays: null,
        productTypes: ["Candy"],
        evidenceSnippet: "Keyword match in product database",
      },
      isVerifiedLead: false,
      isExcluded: false,
      country: "China",
      last_seen_date: null,
      shipment_count_12m: 0,
      _intel: {
        product_count: 15,
        price_coverage_pct: 45,
        last_seen_days: null,
      },
      _enrichment: null,
      _profile: {
        country: "China",
        last_seen_date: null,
        shipment_count_12m: 0,
        role: "Manufacturer",
        role_reason: null,
      },
      _supplierType: "Manufacturer",
      _companyType: "Manufacturer",
      _exampleProducts: [],
    },
  ],
  _excludedMatches: [],
  _supplierRecommendedCount: 2,
  _supplierCandidateCount: 1,
  _supplierExcludedCount: 0,
  // Category factories
  categoryFactories: [
    {
      id: "factory-1",
      name: "Shanghai Confectionery Co., Ltd.",
      location: "Shanghai, China",
      specialization: "Gummies & Jellies",
      establishedYear: 2010,
      certifications: ["FDA", "HACCP", "ISO 22000"],
      minOrder: 2000,
      leadTime: "35-40 days",
      sampleAvailable: true,
    },
    {
      id: "factory-2",
      name: "Guangzhou Sweet Manufacturing",
      location: "Guangzhou, China",
      specialization: "Confectionery Products",
      establishedYear: 2015,
      certifications: ["FDA", "BRC"],
      minOrder: 1500,
      leadTime: "40-45 days",
      sampleAvailable: true,
    },
    {
      id: "factory-3",
      name: "Shenzhen Candy Factory",
      location: "Shenzhen, China",
      specialization: "Candy & Snacks",
      establishedYear: 2008,
      certifications: ["FDA"],
      minOrder: 1000,
      leadTime: "45-50 days",
      sampleAvailable: false,
    },
  ],
  // Input status with photos and origin
  inputStatus: {
    productPhotoUploaded: true,
    barcodePhotoUploaded: true,
    labelPhotoUploaded: true,
    barcodeDecoded: true,
    labelOcrStatus: "success",
    labelOcrFailureReason: null,
    unitWeight: 140,
    shelfPrice: null,
    unitsPerCase: 72,
    countryOfOrigin: "CN",
    originConfirmed: true,
    weightDefaultUsed: false,
    boxSizeDefaultUsed: false,
    labelExtractionSource: "OCR",
    labelExtractionStatus: "CONFIRMED",
    labelConfirmedAt: "2024-02-15T12:00:00.000Z",
    labelConfirmedFields: {
      country_of_origin: "CN",
      allergens_list: ["Gelatin"],
      net_weight_value: 140,
      net_weight_unit: "g",
    },
  },
  // Proof data
  _proof: {
    hsCode: "1704.90",
    hsConfidence: 92,
    labelTerms: ["Gelatin", "Sugar", "Natural flavors", "Citric acid", "Natural colors"],
    labelUploaded: true,
    labelOcrStatus: "SUCCESS",
    labelOcrFailureReason: null,
    labelTermsFromDb: ["Gelatin", "Sugar", "Natural flavors", "Citric acid", "Natural colors"],
    labelOcrCheckedAt: "2024-02-15T12:00:00.000Z",
    similarImportsCount: 42,
    exactImportsCount: 12,
    leadsCount: 3,
    evidenceLevel: "high",
    inputStatus: {
      productPhotoUploaded: true,
      barcodePhotoUploaded: true,
      labelPhotoUploaded: true,
      barcodeDecoded: true,
      labelOcrStatus: "success",
      unitWeight: 140,
      unitsPerCase: 72,
      countryOfOrigin: "CN",
      originConfirmed: true,
      weightDefaultUsed: false,
      boxSizeDefaultUsed: false,
    },
  },
  // Draft inference
  draftInference: {
    weightDraft: {
      value: 140,
      unit: "g",
      confidence: 0.68,
      evidenceSnippet: "From category defaults",
    },
    casePackDraft: {
      candidates: [
        { value: 72, confidence: 0.75, evidenceSnippet: "Standard retail pack configuration" },
        { value: 144, confidence: 0.45, evidenceSnippet: "Alternative bulk pack" },
      ],
      chosen: 72,
      confirmed: false,
    },
    customsCategoryDraft: {
      value: "Sugar confectionery",
      confidence: 0.85,
      evidenceSnippet: "HS code 1704.90 classification",
    },
    hsCandidatesDraft: [
      { code: "1704.90", confidence: 0.92, rationale: "Sugar confectionery", evidenceSnippet: "Matched from exact import records" },
      { code: "1901.90", confidence: 0.72, rationale: "Food preparations", evidenceSnippet: "Alternative classification" },
    ],
  },
  weightDraft: {
    value: 140,
    unit: "g",
    confidence: 0.68,
    evidenceSnippet: "From category defaults",
  },
  casePackDraft: {
    candidates: [
      { value: 72, confidence: 0.75, evidenceSnippet: "Standard retail pack configuration" },
      { value: 144, confidence: 0.45, evidenceSnippet: "Alternative bulk pack" },
    ],
    chosen: 72,
    confirmed: false,
  },
  customsCategoryDraft: {
    value: "Sugar confectionery",
    confidence: 0.85,
    evidenceSnippet: "HS code 1704.90 classification",
  },
  hsCandidatesDraft: [
    { code: "1704.90", confidence: 0.92, rationale: "Sugar confectionery", evidenceSnippet: "Matched from exact import records" },
    { code: "1901.90", confidence: 0.72, rationale: "Food preparations", evidenceSnippet: "Alternative classification" },
  ],
  // Decision support data
  _decisionSupport: {
    hs: {
      customsCategoryText: "Sugar confectionery (including white chocolate), not containing cocoa",
      status: "DRAFT",
      candidates: [
        {
          code: "1704.90",
          confidence: 92,
          rationale: "Sugar confectionery - confirmed from exact import records",
          evidenceSnippet: "12 exact import records match this HS code for fruit gummies variety pack",
          source: "EXACT_IMPORT",
        },
        {
          code: "1901.90",
          confidence: 72,
          rationale: "Food preparations of goods - alternative classification",
          evidenceSnippet: "Alternative classification for prepared food items",
          source: "FALLBACK",
        },
      ],
      hybridPaths: [
        {
          code: "1704.90",
          label: "Sugar confectionery (primary)",
          when: "Product contains sugar as primary ingredient",
          confidence: 92,
        },
        {
          code: "1901.90",
          label: "Food preparations (alternative)",
          when: "If product is classified as prepared food",
          confidence: 72,
        },
      ],
      decisionRule: "Use 1704.90 if sugar content > 50%, otherwise consider 1901.90",
    },
    dutyRate: {
      rateMin: 8.5,
      rateMax: 9.5,
      rationale: "Standard duty rate for sugar confectionery from China (MFN rate)",
      status: "DRAFT",
    },
    cost: {
      unitPriceRange: { min: 1.08, max: 1.35 },
      shippingRange: { min: 0.38, max: 0.68 },
      dutyRange: { min: 0.10, max: 0.16 },
      feeRange: { min: 0.04, max: 0.07 },
      totalLandedCostRange: { min: 1.62, max: 2.32 },
    },
    quantityPlanner: {
      moqRange: { min: 1000, max: 5000, typical: 2000 },
      leadTimeRange: { min: 28, max: 55, typical: 40 },
      recommendedOrderQuantity: 2000,
    },
    profit: {
      estimatedMarginRange: { min: 0.25, max: 0.45 },
      breakEvenQuantity: 500,
    },
    nexsupplyValue: {
      timeToQuote: "5-7 days",
      verificationBenefits: [
        "Confirmed HS code and duty rate",
        "3 verified factory quotes with MOQ",
        "Label compliance check",
        "Origin documentation",
      ],
    },
  },
  // Additional extraction fields
  hasBarcodeImage: true,
  hasLabelImage: true,
  barcodeValue: "012345678901",
  weightGrams: 140,
  originCountry: "CN",
  labelTerms: ["Gelatin", "Sugar", "Natural flavors", "Citric acid", "Natural colors"],
  labelTextPresent: true,
};
